#!/bin/sh

ACTIVE_MONITOR=$(xrandr --listactivemonitors | sed '1 d' | awk 'NF>1{print $NF}')

bspc monitor $ACTIVE_MONITOR -d 1 2 3 4 5 6 7 8 9

bspc config focus_follows_pointer true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

bspc config split_ratio 0.5

# BORDERS + GAPS

bspc config border_width 0
bspc config window_gap   0
bspc config top_padding 80

bspc config single_monocle      true
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# RULES

bspc rule -a mpv state=floating
bspc rule -a Sxiv state=floating
bspc rule -a chromium desktop='^1'
bspc rule -a slack desktop='3'

# UTILS

killall sxhkd 2> /dev/null
sxhkd &
$HOME/.config/polybar/launch.sh &
$HOME/.config/picom/launch.sh &
setxkbmap -option ctrl:nocaps

# vim: ft=sh
