#!/bin/sh

# TODO/andrew: move this
# get the resize/move commands
export PATH=$HOME/bin:$PATH

#ACTIVE_MONITOR=$(xrandr --listactivemonitors | sed '1 d' | awk 'NF>1{print $NF}')

#bspc monitor $ACTIVE_MONITOR -d 1 2 3 4 5 6 7 8 9

# set an increased scale if just one monitor
#if [ $monitors -lt 2 ]; then 
	#xrandr --output eDP1 --mode 2560x1440 --scale 1.1x1.1
	#bspc monitor eDP1 -d I II III
#else
	xrandr --output eDP1 --mode 2048x1152 --scale 1.0x1.0
	xrandr --output DP1 --mode 3840x2160 --scale 1.0x1.0 --right-of eDP1
	bspc monitor eDP1 -d I II III
	bspc monitor DP1 -d IV V VI
#fi

#bspc config focus_follows_pointer true
bspc config click_to_focus 	 true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

# BORDERS + GAPS

bspc config border_width        2
bspc config window_gap          6
bspc config top_padding         42

bspc config single_monocle      true
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config split_ratio         0.50

# RULES

# TODO/andrew: make sure these work
#bspc rule -a mpv state=floating
#bspc rule -a Sxiv state=floating
#bspc rule -a chromium desktop='^1'
#bspc rule -a slack desktop='3'

# RUN UTILS

killall sxhkd 2> /dev/null
sxhkd &
$HOME/.config/polybar/launch.sh &
$HOME/.config/picom/launch.sh &
setxkbmap -option ctrl:nocaps

# vim: ft=sh
